title: Wijkraad Koningshaven
description: "De Stichting Wijkraad Koningshaven heeft o.a. als doel het
  bevorderen van het welzijn van de bewoners van de wijken Broekhoven 1, Fatima
  en Hoogvenne. De Stichting Wijkraad Koningshaven heeft geen winstoogmerk. "
logo: /images/logo.svg
image: /images/main-img.jpg
email: info@wijkraadkoningshaven.nl
links:
  - title: Wijkkrant Koningshaven
    url: https://wijkkrantkoningshaven.nl/
socials:
  - title: whatsapp
    icon: icofont-whatsapp
    link: whatsapp://0643933867
  - title: facebook
    icon: icofont-facebook
    link: https://www.facebook.com/profile.php?id=100086683593910
