title: Wijkraad Koningshaven
description: |
  test
logo: /images/logo.svg
image: /images/main-img.jpg
email: info@wijkraadkoningshaven.nl
links:
  - title: Wijkkrant Koningshaven
    url: https://wijkkrant.koningshaven.eu/
socials:
  - title: whatsapp
    icon: icofont-whatsapp
    link: whatsapp://0643933867
  - title: facebook
    icon: icofont-facebook
    link: https://www.facebook.com/Koningshaven.eu/
