title: Wijkraad Koningshaven
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
  veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
  commodo consequat.
logo: /images/logo.svg
image: /images/main-img.jpg
email: info@wijkraadkoningshaven.nl
links:
  - title: Wijkkrant Koningshaven
    url: https://wijkkrant.koningshaven.eu/
socials:
  - title: whatsapp
    icon: icofont-whatsapp
    link: whatsapp://0643933867
  - title: facebook
    icon: icofont-facebook
    link: https://www.facebook.com/Koningshaven.eu/
