title: Wijkraad Koningshaven
description: >
  Alle aanvragen worden door het bestuur van Stichting Wijkraad Koningshaven
  besproken. Het gehele bestuur beslist of de aanvraag wordt toegekend en welk
  bedrag zij subsidiëren.
logo: /images/logo.svg
image: /images/main-img.jpg
email: info@wijkraadkoningshaven.nl
links:
  - title: Wijkkrant Koningshaven
    url: https://wijkkrant.koningshaven.eu/
socials:
  - title: whatsapp
    icon: icofont-whatsapp
    link: whatsapp://0643933867
  - title: facebook
    icon: icofont-facebook
    link: https://www.facebook.com/Koningshaven.eu/
