title: Stichting Wijkraad Koningshaven
description: >
  De stichting wijkraad Koningshaven is op 1 januari 1995 opgericht en
  ingeschreven in de Kamer van Koophandel.

  De wijkraad is een stichting zonder winstbejag en ontvangt een subsidie van de gemeente Tilburg om de verbinding tussen wijkbewoners te bevorderen. Daarnaast is de wijkraad ook een spreekbuis tussen de gemeente Tilburg en de wijkbewoners Broekhoven 1 - Fatima en Hoogvenne.
logo: /uploads/logo.svg
image: /img/main-img.jpg
email: info@wijkraadkoningshaven.nl
links:
  - title: Wijkkrant Koningshaven
    url: https://wijkkrant.koningshaven.eu/
socials:
  - title: whatsapp
    icon: icofont-whatsapp
    link: whatsapp://0643933867
  - title: facebook
    icon: icofont-facebook
    link: https://www.facebook.com/Koningshaven.eu/
