title: Wijkraad Koningshaven
description: Een wijkraad met een hart voor de wijk
logo: /uploads/logo.svg
image: /img/main-img.jpg
email: info@wijkraadkoningshaven.nl
whatsapp: 0643933867
links:
  - name: Wijkkrant Koningshaven
    link: https://wijkkrant.koningshaven.eu/

