media:
  input: "_src/static/uploads"
  output: "uploads"

content:
  - name: "settings"
    label: "Website settings"
    path: "_src/_data/site.yml"
    type: file
    fields:
      - { name: "logo", label: "Naam", type: "image" }
      - { name: "name", label: "Naam", type: "string" }
      - { name: "description", label: "Beschrijving", type: "string" }
      - name: "metas"
        label: "metas"
        type: "object"
        fields:
          - { name: "title", label: "Title", type: "string" }
          - { name: "description", label: "Description", type: "string" }
          - { name: "icon", label: "Icon", type: "image" }
          - { name: "lang", label: "Language", type: "string" }
          - { name: "generator", label: "Generator", type: "boolean" }

  - name: "posts"
    label: "Nieuws posts"
    path: "_src/nieuws"
    type: collection
    view: 
      fields: [ image, title ]
    fields:
      - { name: "draft", label: "Draft", type: "boolean", default: true }
      - { name: "title", label: "Title", type: "string" }
      - { name: "summery", label: "Summery", type: "text" }
      - { name: "image", label: "Image", type: "image" }
      - { name: "body", label: "Body", type: rich-text }

  - name: "events"
    label: "agenda"
    path: "_src/agenda"
    type: collection
    view: 
      fields: [ image, title ]
    fields:
      - { name: "draft", label: "Draft", type: "boolean", default: true }
      - name: "createdAt"
        label: "Published date"
        type: "date"
        options:
          format: "MM-dd-yyyy"
          min: "2023-12-24"
        
      - { name: "title", label: "Title", type: "string" }
      - { name: "description", label: "Description", type: "text" }
      - { name: "image", label: "Image", type: "image" }
      - { name: "body", label: "Body", type: rich-text }

      - name: "event"
        label: "Event information"
        type: object
        fields:
          - { name: "time", label: "Time", type: "string" }
          - { name: "location", label: "Lokatie", type: "string" }
          - { name: "price", label: "Prijs", type: "string" }
          - { name: "date", label: "Datum", type: "date" }