media: "_src/static/uploads"

content:
  - name: "settings"
    label: "Website settings"
    path: "_src/_data/site.yml"
    type: file
    fields:
      - name: "logo"
        label: "Logo"
        type: image
        options:
          extensions: [svg]
      - { name: "name", label: "Naam", type: "string" }
      - { name: "description", label: "Beschrijving", type: "string" }
      - name: "metas"
        label: "metas"
        type: object
        fields:
          - { name: "title", label: "Title", type: "string" }
          - { name: "description", label: "Description", type: "string" }
          - { name: "icon", label: "Icon", type: "image" }
          - { name: "lang", label: "Language", type: "string" }
          - { name: "generator", label: "Generator", type: "boolean" }

  - name: "posts"
    label: "Nieuws posts"
    path: "_src/nieuws"
    type: collection
    view: 
      fields: [ image, title ]
    fields:
      - { name: "draft", label: "Draft", type: boolean, default: true }
      - { name: "title", label: "Title", type: string }
      - { name: "summery", label: "Summery", type: text }
      - { name: "image", label: "Image", type: image }
      - { name: "body", label: "Body", type: rich-text }

  - name: "agenda"
    label: "agenda"
    path: "_src/agenda"
    type: collection
    view: 
      fields: [ image, title ]
    fields:
      - { name: "draft", label: "Draft", type: boolean, default: true }
      - name: "createdAt"
        label: "Published date"
        type: date
        options:
          format: dd-MM-yyyy
        
      - { name: "title", label: "Title", type: string }
      - { name: "description", label: "Description", type: text }
      - { name: "image", label: "Image", type: image }
      - { name: "body", label: "Body", type: rich-text }

      - name: "event"
        label: "Event information"
        type: object
        fields:
          - { name: "time", label: "Time", type: string }
          - { name: "location", label: "Lokatie", type: string }
          - { name: "price", label: "Prijs", type: string }
          - name: "date"
            label: "Datum"
            type: date
            options:
              format: dd-MM-yyyy
              time: true

  - name: "albums"
    label: "Albums"
    path: "_src/albums"
    type: collection
    view: 
      fields: [ title, image ]
    fields:
      - { name: "title", label: "Title", type: "string" }
      - { name: "description", label: "Description", type: "string" }
      - { name: "cover_image", label: "Cover image", type: "image" }
      - name: "album_images"
        label: "Images"
        type: image
        options:
          multiple: true