[build]
    publish = "_site"
    command = """
        curl -fsSL https://deno.land/install/install.sh | sh && \
        /opt/buildhome/.deno/bin/deno task build \
    """


[[redirects]]
    from = "/*"
    status = 404
    to = "/404"
