backend:
  name: git-gateway
  branch: main
  # repo: MadebyMonkeys/wijkraadkoningshaven.nl
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

publish_mode: editorial_workflow

media_folder: "/static/uploads"
public_folder: "/uploads"

collections:
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "_data/site.yml"
        description: "General Site Settings"
        fields:
          - { label: "Global title", name: "title", widget: "string" }
          - { label: "Global description", name: "description", widget: "text" }
          - { label: "Logo", name: "logo", widget: "image", default: "/img/logo.svg" }




  - name: "pages"
    label: "Pages"
    files:
      - name: "landing"
        label: "Landing"
        file: "/index.yml"
        editor:
          preview: false
        fields:
          - name: "hero"
            label: "Hero"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "description", label: "Description", widget: "markdown" }

          - name: "about"
            label: "About"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string"}
              - { name: "image", label: "Image", widget: "image" }
              - { name: "content", label: "Content", widget: "markdown" }


      - name: "over ons"
        label: "Over ons"
        file: "/over-ons.yml"
        editor:
          preview: false
        fields:
          - name: "about"
            label: "About"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "image", label: "Image", widget: "image" }
              - { name: "content", label: "Content", widget: "markdown" }


      - name: "verrijk je wijk"
        label: "Verrijk je wijk"
        file: "/verrijk-je-wijk.yml"
        editor:
          preview: false
        fields:
          - name: "vjw"
            label: "Verrijk je wijk"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "image", label: "Image", widget: "image" }
              - { name: "content", label: "Content", widget: "markdown" }



  - name: "post"
    label: "Post"
    folder: "/nieuws/"
    public_folder: "/uploads/"
    description: "Create or edit news post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/nieuws-post.vto" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Publish date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", hint: "Plaats nieuws bericht hier" }
        



  - name: "evenement"
    label: "Event"
    folder: "/events/"
    public_folder: "/uploads/"
    description: "Create or edit an event"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/event-post.vto" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Publish date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Event Date", name: "event_date", widget: "datetime" }
      - { label: "Event Price", name: "price", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
