title: Wijkraad Koningshaven
description: Een wijkraad met een hart voor de wijk
logo: /uploads/logo.svg
email: info@wijkraadkoningshaven.nl
links:
  - title: Wijkkrant Koningshaven
    url: https://wijkkrant.koningshaven.eu/
socials:
  - title: whatsapp
    link: whatsapp://0643933867
  - title: facebook
    link: https://facebook.com/Koningshaven.eu/
