

backend:
  name: "git-gateway"
  branch: "main"

# local_backend:
#   url: http://localhost:8082/api/v1

media_folder: "static/images/uploads" # Media files will be stored here
public_folder: "/images/uploads" # Public URL for the images

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: "/posts/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured image", name: "featured_image", widget: "image", required: false }

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    path: "{{slug}}/index"  # Ensure that index.md is created in the gallery folder
    media_folder: ""        # Ensures images are uploaded in the same folder as the index.md
    public_folder: "/gallery/{{slug}}"  # Public path for accessing the images
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { 
          label: "Gallery Images", 
          name: "gallery_images", 
          widget: "image", 
          multiple: true,  # Allows multiple image uploads
          required: false, 
          media_library: {
            config: {
              multiple: true  # Allows bulk image uploads
            }
          }
        }


  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured image", name: "featured_image", widget: "image", required: false }
      - { label: "Event Date", name: "event_date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Register link", name: "registration_link", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  
  - name: "home"
    label: "Home Page Settings"
    create: false  # No new files, only editing existing ones
    files:
      - label: "Hero Section"
        name: "hero"
        file: "data/home/hero.yml"  # Path to the hero.yml file
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }

      - label: "About Section"
        name: "about"
        file: "data/home/about.yml"  # Path to the about.yml file
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }

      - label: "Features Section"
        name: "features"
        file: "data/home/features.yml"  # Path to the features.yml file
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Features List", name: "features_list", widget: "list", 
              fields: 
                [
                  { label: "Feature Title", name: "title", widget: "string" },
                  { label: "Feature Description", name: "description", widget: "text" }
                ]
            }

  - name: "about"
    label: "About Page"
    folder: "content/about"  # Folder containing the _index.md file
    create: false            # Do not create new folders
    slug: "about"           # This will be the slug for the about page
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }

  - name: "contact"
    label: "Contact Page"
    folder: "content/contact"  # Folder containing the _index.md file
    create: false            # Do not create new folders
    slug: "contact"           # This will be the slug for the about page
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "Verrijk je wijk"
    label: "Verrijk je wijk Page"
    folder: "content/verrijk-je-wijk"  # Folder containing the _index.md file
    create: false            # Do not create new folders
    slug: "verrijk-je-wijk"           # This will be the slug for the about page
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
